### ISSUE TITLE
@relpath prevents using "compute" outside the benchmark script

### ISSUE THREAD

**Issue by schillic** [JuliaReach/ReachabilityBenchmarks#14]
See any SLICOT model.

**Comment by mforets** [comment]
This is fixed by [#135](https://github.com/JuliaReach/Reachability.jl/pull/135) in the sense that i can now copy-paste, say `iss.jl` into a jupyter notebook, run the notebook and it will work. before, it was generating "/out.mat" instead of just "out.mat". don't know if this is the use case that you had in mind.

**Comment by schillic** [comment]
Unfortunately, this did not fix the problem. Now I get this:
```julia
ERROR: MethodError: no method matching split(::Void, ::String)
```

**Comment by schillic** [comment]
My use case was this:
```julia
# load data, define the 'compute' function
include("motor.jl")
# use the 'compute' function outside of the benchmark script
compute(:δ => 1e-3, :T => 20.0, :mode=>"reach")
```
It crashes when plotting (where `@relpath` is used).

**Comment by mforets** [comment]
Alright, i think [this](https://github.com/JuliaReach/Reachability.jl/compare/c4a417bef6eb...b0cc5f3d9ad7) should make it.
